"""Rendering for the run summary and the committed eval report.

Output is plain text for the run summary and Markdown for the eval report. Both
state what is true without dressing it up, and the eval report shows the gated
metric and whether it passed, not a single headline number.
"""

from __future__ import annotations

from constituent_reconciler.evaluate import EvalReport
from constituent_reconciler.models import RunResult


def render_run_summary(result: RunResult, *, withheld: int = 0) -> str:
    n_records = len(result.records)
    n_clusters = len(result.clusters)
    merged_clusters = sum(1 for c in result.clusters if len(c.members) > 1)
    lines = [
        f"records read:        {n_records}",
        f"candidate pairs:     {len(result.pairs)}",
        f"auto-merged pairs:   {len(result.auto_pairs)}",
        f"pairs to review:     {len(result.review_pairs)}",
        f"resolved records:    {n_clusters} ({merged_clusters} formed by merging)",
    ]
    if withheld:
        lines.append(f"withheld (no consent): {withheld}")
    return "\n".join(lines)


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _ci(interval: tuple[float, float]) -> str:
    low, high = interval
    return f"[{_pct(low)}, {_pct(high)}]"


def render_eval_markdown(report: EvalReport, *, dataset: str, gate_threshold: float = 0.0) -> str:
    gate_pass = report.false_merge_rate <= gate_threshold
    gate_word = "PASS" if gate_pass else "FAIL"

    lines = [
        "# Eval report",
        "",
        f"Dataset: `{dataset}`. Generated by `reconcile eval`. This file is "
        "committed and regenerated on release. Numbers come from running the "
        "matcher on seeded synthetic fixtures with planted ground truth; there is "
        "no real personal data in the fixtures.",
        "",
        "## Why these metrics",
        "",
        "A false merge joins two different people and can corrupt a record "
        "irreversibly. A missed match leaves a duplicate, which is recoverable. "
        "The two errors are not equal, so the gated metric is the false-merge "
        "rate among auto-merged pairs, and it is reported with a Wilson "
        "confidence interval because the denominator is small.",
        "",
        "## Results",
        "",
        "| Metric | Value | 95% CI |",
        "|--------|-------|--------|",
        f"| Records | {report.n_records} | |",
        f"| True duplicate pairs (ground truth) | {report.n_true_pairs} | |",
        f"| Candidate pairs after blocking | {report.n_candidate_pairs} | |",
        f"| Auto-merged pairs | {report.n_auto} | |",
        f"| Pairs sent to review | {report.n_review} | |",
        f"| **False-merge rate (gated)** | **{_pct(report.false_merge_rate)}** "
        f"({report.false_merges}/{report.n_auto}) | {_ci(report.false_merge_ci)} |",
        f"| Missed-match rate | {_pct(report.missed_match_rate)} "
        f"({report.missed}/{report.n_true_pairs}) | {_ci(report.missed_match_ci)} |",
        f"| Precision, auto | {_pct(report.precision_auto)} | |",
        f"| Recall, auto | {_pct(report.recall_auto)} | |",
        f"| Precision, auto+review coverage | {_pct(report.precision_coverage)} | |",
        f"| Recall, auto+review coverage | {_pct(report.recall_coverage)} | |",
        f"| Blocking misses (true pairs never scored) | {report.blocking_misses} | |",
        "",
        "## Gate",
        "",
        f"False-merge gate at threshold {_pct(gate_threshold)}: **{gate_word}** "
        f"(observed {_pct(report.false_merge_rate)}).",
        "",
        "Recall at the auto level is intentionally below 100%: pairs the matcher "
        "is unsure about are not auto-merged, they are sent to review. The "
        "auto+review coverage recall is the share of true duplicates the system "
        "surfaces to a human one way or another.",
    ]
    return "\n".join(lines) + "\n"
