"""Rendering for the run summary and the committed eval report.

Output is plain text for the run summary and Markdown for the eval report. Both
state what is true without dressing it up, and the eval report shows the gated
metric and whether it passed, not a single headline number.
"""

from __future__ import annotations

from constituent_reconciler.evaluate import EvalReport, ExtractionReport
from constituent_reconciler.models import RunResult


def render_run_summary(result: RunResult, *, withheld: int = 0) -> str:
    n_records = len(result.records)
    n_clusters = len(result.clusters)
    merged_clusters = sum(1 for c in result.clusters if len(c.members) > 1)
    lines = [
        f"records read:        {n_records}",
        f"candidate pairs:     {len(result.pairs)}",
        f"auto-merged pairs:   {len(result.auto_pairs)}",
        f"pairs to review:     {len(result.review_pairs)}",
        f"resolved records:    {n_clusters} ({merged_clusters} formed by merging)",
    ]
    if withheld:
        lines.append(f"withheld (no consent): {withheld}")
    return "\n".join(lines)


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _ci(interval: tuple[float, float]) -> str:
    low, high = interval
    return f"[{_pct(low)}, {_pct(high)}]"


def render_eval_markdown(report: EvalReport, *, dataset: str, gate_threshold: float = 0.0) -> str:
    gate_pass = report.false_merge_rate <= gate_threshold
    gate_word = "PASS" if gate_pass else "FAIL"

    lines = [
        "# Eval report",
        "",
        f"Dataset: `{dataset}`. Generated by `reconcile eval`. This file is "
        "committed and regenerated on release. Numbers come from running the "
        "matcher on seeded synthetic fixtures with planted ground truth; there is "
        "no real personal data in the fixtures.",
        "",
        "## Why these metrics",
        "",
        "A false merge joins two different people and can corrupt a record "
        "irreversibly. A missed match leaves a duplicate, which is recoverable. "
        "The two errors are not equal, so the gated metric is the false-merge "
        "rate among auto-merged pairs, and it is reported with a Wilson "
        "confidence interval because the denominator is small.",
        "",
        "## Results",
        "",
        "| Metric | Value | 95% CI |",
        "|--------|-------|--------|",
        f"| Records | {report.n_records} | |",
        f"| True duplicate pairs (ground truth) | {report.n_true_pairs} | |",
        f"| Candidate pairs after blocking | {report.n_candidate_pairs} | |",
        f"| Auto-merged pairs | {report.n_auto} | |",
        f"| Pairs sent to review | {report.n_review} | |",
        f"| **False-merge rate (gated)** | **{_pct(report.false_merge_rate)}** "
        f"({report.false_merges}/{report.n_auto}) | {_ci(report.false_merge_ci)} |",
        f"| Missed-match rate | {_pct(report.missed_match_rate)} "
        f"({report.missed}/{report.n_true_pairs}) | {_ci(report.missed_match_ci)} |",
        f"| Precision, auto | {_pct(report.precision_auto)} | |",
        f"| Recall, auto | {_pct(report.recall_auto)} | |",
        f"| Precision, auto+review coverage | {_pct(report.precision_coverage)} | |",
        f"| Recall, auto+review coverage | {_pct(report.recall_coverage)} | |",
        f"| Blocking misses (true pairs never scored) | {report.blocking_misses} | |",
        "",
        "## Gate",
        "",
        f"False-merge gate at threshold {_pct(gate_threshold)}: **{gate_word}** "
        f"(observed {_pct(report.false_merge_rate)}).",
        "",
        "Recall at the auto level is intentionally below 100%: pairs the matcher "
        "is unsure about are not auto-merged, they are sent to review. The "
        "auto+review coverage recall is the share of true duplicates the system "
        "surfaces to a human one way or another.",
    ]
    return "\n".join(lines) + "\n"


def render_extraction_markdown(
    report: ExtractionReport,
    *,
    dataset: str,
    precision_target: float = 0.95,
    recall_target: float = 0.90,
) -> str:
    precision_ok = report.precision >= precision_target
    recall_ok = report.recall >= recall_target
    verdict = "MET" if precision_ok and recall_ok else "NOT MET"

    lines = [
        "# Extraction eval report",
        "",
        f"Fixture set: `{dataset}`. Generated by `reconcile eval-extraction`. "
        "This file is committed and regenerated when the extractor or the "
        "labeled fixtures change. The fixtures are deterministic synthetic "
        "intake forms with hand-written ground-truth labels; there is no real "
        "personal data in them.",
        "",
        "## What is measured",
        "",
        "Field-level precision and recall of the offline PDF extractor. A "
        "predicted field is correct when its field name and normalized value "
        "match a labeled field in the same document, using the same "
        "normalizers the matching pipeline applies, so formatting differences "
        "do not count as errors. Unmatched predictions are false positives; "
        "unmatched labels are false negatives. This is a REVIEW metric in the "
        "metrics ledger, read by a person, and a test also holds the committed "
        "fixture at or above the ledger targets so the numbers cannot drift "
        "silently.",
        "",
        "## Results",
        "",
        "| Metric | Value | 95% CI |",
        "|--------|-------|--------|",
        f"| Documents | {report.n_docs} | |",
        f"| Labeled fields (ground truth) | {report.n_truth_fields} | |",
        f"| Predicted fields | {report.n_predicted_fields} | |",
        f"| Precision | {_pct(report.precision)} "
        f"({report.tp}/{report.tp + report.fp}) | {_ci(report.precision_ci)} |",
        f"| Recall | {_pct(report.recall)} "
        f"({report.tp}/{report.tp + report.fn}) | {_ci(report.recall_ci)} |",
        "",
        "## Per-field breakdown",
        "",
        "| Field | TP | FP | FN | Precision | Recall |",
        "|-------|----|----|----|-----------|--------|",
    ]
    for name, score in sorted(report.per_field.items()):
        lines.append(
            f"| {name} | {score.tp} | {score.fp} | {score.fn} "
            f"| {_pct(score.precision)} | {_pct(score.recall)} |"
        )
    lines += [
        "",
        "## Targets",
        "",
        f"Ledger targets: precision at least {_pct(precision_target)}, recall "
        f"at least {_pct(recall_target)}. Observed: precision "
        f"{_pct(report.precision)}, recall {_pct(report.recall)}. **{verdict}**.",
    ]
    if report.fn > 0:
        lines += [
            "",
            f"False negatives ({report.fn} here) are shown, not hidden: the "
            "fixture set deliberately includes at least one field the "
            "deterministic extractor is known not to parse (see the fixture "
            "README), so the measurement demonstrably catches a real miss "
            "rather than scoring a set the extractor is guaranteed to ace.",
        ]
    return "\n".join(lines) + "\n"
