"""Recipe scaffolding for ``constituent-reconcile init``.

The adoption kit asks a non-technical operator to write ``recipe.toml`` by hand
(``docs/ADOPTION-KIT.md`` Step 2). ``validate`` catches a mistake afterwards but
does nothing to help write the file, and the first recipe is where pilots stall.

This module reads the header row of the operator's own CSVs and writes a starter
recipe from what it finds. What it deliberately does **not** do is the whole
point of it.

**It never reads past the header.** A scaffold that inferred a date-of-birth
column from the shape of its values would be making a decision about someone's
data on the strength of a regular expression, silently, in a file the operator is
about to trust. Header text is the operator's own label for the column, so
matching it is reading what they wrote rather than guessing what they meant.

**It maps only on an exact, documented alias.** :data:`ALIASES` is a closed table,
published in the adoption kit, matched case-insensitively after collapsing
whitespace and nothing more. No fuzzy matching, no edit distance, no substrings:
``"Client First"`` is not ``"First Name"``, and pretending otherwise would put a
mapping in the file that nobody chose. Everything else becomes a commented stub
with the real column names listed beside it.

**It refuses when two columns claim the same field.** If a run has both a
``"First Name"`` and an ``"fname"`` column, there is no basis here for preferring
one, so the field is left as a stub naming both candidates. Choosing would be a
guess wearing the clothes of a default.

**The file it writes does not run.** ``[policy] pack`` is written empty, which
:func:`~constituent_reconciler.policy.policy_for` rejects, so the scaffold fails
``constituent-reconcile validate`` until a person has chosen a policy pack. That
is not an oversight to be smoothed over later: the pack decides whether personal
data may leave the machine, and it is not a field a generator gets to default.
"""

from __future__ import annotations

import csv
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

from constituent_reconciler.models import CANONICAL_FIELDS

#: The line every generated recipe starts with. ``validate`` looks for it before
#: offering scaffold-specific advice, so the hint is only ever shown about a file
#: this module actually wrote.
GENERATED_MARKER = "# Generated by `constituent-reconcile init`."

#: The value ``[policy] pack`` is scaffolded with. Empty is not a default: no
#: policy pack is named ``""``, so the recipe cannot load until a person picks one.
UNCHOSEN_POLICY_PACK = ""

#: Exact column-header aliases per canonical field. Matched case-insensitively
#: after collapsing internal whitespace, and in no other way. Adding an alias is a
#: documentation change as much as a code change: ``docs/ADOPTION-KIT.md`` prints
#: this table, and ``tests/test_scaffold.py`` asserts the two agree.
#:
#: The bar for an entry is that the header means the canonical field and nothing
#: else in a human-services export. ``"name"`` is absent for that reason -- it is
#: a full name at least as often as a first name -- and so is ``"date"``.
ALIASES: dict[str, tuple[str, ...]] = {
    "first_name": ("first name", "firstname", "fname", "first", "given name", "givenname"),
    "last_name": ("last name", "lastname", "lname", "last", "surname", "family name"),
    "dob": ("dob", "date of birth", "birth date", "birthdate", "birthday"),
    "email": ("email", "e-mail", "email address", "emailaddress"),
    "phone": ("phone", "phone number", "telephone", "mobile", "cell", "cell phone"),
    "address": ("address", "street", "street address", "address line 1", "address1"),
}

#: Aliases for the consent column, kept apart from :data:`ALIASES` because consent
#: is not a canonical matching field: it is the gate the write step reads.
CONSENT_ALIASES: tuple[str, ...] = ("consent", "consent status", "consent flag", "opt in", "optin")

#: Aliases for the stable per-row id, likewise not a matching field.
ID_ALIASES: tuple[str, ...] = ("id", "record id", "recordid", "client id", "constituent id")


class ScaffoldError(ValueError):
    """A source could not be inspected, or the destination already exists."""


def normalize_header(header: str) -> str:
    """The comparison form of a column header: casefolded, whitespace collapsed.

    Deliberately weak. It absorbs the difference between ``"First Name"``,
    ``"first  name"`` and ``"FIRST NAME"`` -- three spellings of one label -- and
    nothing else. Punctuation is significant, so ``"first_name"`` and
    ``"first-name"`` are distinct headers unless the alias table lists them.
    """

    return " ".join(header.split()).casefold()


def _match(headers: Sequence[str], aliases: Iterable[str]) -> tuple[str | None, list[str]]:
    """The single header matching ``aliases``, plus every candidate that matched.

    Returns ``(None, candidates)`` when nothing matched or when more than one
    distinct header did. Two candidates is an ambiguity a person resolves, not a
    tie this module breaks.
    """

    alias_set = set(aliases)
    candidates = sorted({h for h in headers if normalize_header(h) in alias_set})
    return (candidates[0] if len(candidates) == 1 else None, candidates)


@dataclass(frozen=True)
class SourceInspection:
    """What was read out of one input path. Header text only -- never a data row."""

    path: Path
    #: Files whose headers were read. One entry for a file, zero or more for a
    #: directory; a directory with no readable CSV yields an empty tuple, which is
    #: reported rather than treated as a source with no columns.
    files: tuple[Path, ...]
    headers: tuple[str, ...]
    #: Extensions seen in a directory but not inspected, so a scaffold built from
    #: two of five files says so instead of implying it saw everything.
    skipped_suffixes: tuple[str, ...]


@dataclass(frozen=True)
class Scaffold:
    """A generated recipe and the decisions it declined to make."""

    text: str
    mapping: dict[str, str]
    #: Canonical fields left as commented stubs, with why: ``"no column matched"``
    #: or the ambiguous candidates.
    stubs: dict[str, str]
    unmapped_columns: tuple[str, ...]
    inspections: tuple[SourceInspection, ...]


def read_headers(path: Path) -> SourceInspection:
    """Read the header row of ``path``, or of every ``.csv`` directly inside it.

    A directory contributes the union of its files' headers, in first-seen order,
    and names the other extensions it found. Only the first line of each file is
    read.
    """

    if path.is_dir():
        files = sorted(p for p in path.iterdir() if p.is_file() and p.suffix.lower() == ".csv")
        skipped = sorted(
            {p.suffix.lower() for p in path.iterdir() if p.is_file() and p.suffix.lower() != ".csv"}
        )
    elif path.is_file():
        files, skipped = [path], []
    else:
        raise ScaffoldError(f"input path does not exist: {path}")

    headers: list[str] = []
    for file in files:
        for header in _header_row(file):
            if header not in headers:
                headers.append(header)
    return SourceInspection(
        path=path,
        files=tuple(files),
        headers=tuple(headers),
        skipped_suffixes=tuple(skipped),
    )


def _header_row(file: Path) -> list[str]:
    """The first row of ``file`` as column names. Reads one line and stops."""

    try:
        # utf-8-sig strips the byte-order mark Excel writes, which would otherwise
        # make the first column header "﻿id" and match no alias.
        with file.open("r", encoding="utf-8-sig", newline="") as handle:
            row = next(csv.reader(handle), [])
    except OSError as error:
        raise ScaffoldError(f"could not read {file}: {error.strerror}") from error
    except UnicodeDecodeError as error:
        raise ScaffoldError(
            f"{file} is not UTF-8 text ({error.reason}); export it as UTF-8 CSV first"
        ) from error
    return [cell.strip() for cell in row if cell.strip()]


def build(
    *,
    incoming: Path,
    existing: Path | None = None,
    recipe_dir: Path,
) -> Scaffold:
    """Inspect the sources and compose the starter recipe.

    ``recipe_dir`` is the directory the recipe will be written to; input paths are
    rendered relative to it where possible, matching how ``load_recipe`` resolves
    them, so the recipe and its data can still be moved together.
    """

    inspections = [read_headers(incoming)]
    if existing is not None:
        inspections.insert(0, read_headers(existing))
    headers: list[str] = []
    for inspection in inspections:
        for header in inspection.headers:
            if header not in headers:
                headers.append(header)

    mapping: dict[str, str] = {}
    stubs: dict[str, str] = {}
    for field in CANONICAL_FIELDS:
        match, candidates = _match(headers, ALIASES[field])
        if match is not None:
            mapping[field] = match
        elif candidates:
            named = ", ".join(repr(c) for c in candidates)
            stubs[field] = f"more than one column could be it: {named}"
        else:
            stubs[field] = "no column header matched a documented alias"

    consent_column, consent_candidates = _match(headers, CONSENT_ALIASES)
    id_column, _ = _match(headers, ID_ALIASES)
    claimed = set(mapping.values()) | ({consent_column} if consent_column else set())
    if id_column is not None:
        claimed.add(id_column)
    unmapped = tuple(h for h in headers if h not in claimed)

    text = _render(
        inspections=inspections,
        mapping=mapping,
        stubs=stubs,
        consent_column=consent_column,
        consent_candidates=consent_candidates,
        id_column=id_column,
        unmapped=unmapped,
        recipe_dir=recipe_dir,
    )
    return Scaffold(
        text=text,
        mapping=mapping,
        stubs=stubs,
        unmapped_columns=unmapped,
        inspections=tuple(inspections),
    )


def _relative(path: Path, base: Path) -> str:
    """``path`` as the recipe should spell it: relative to the recipe's directory."""

    try:
        return path.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _source_comment(inspection: SourceInspection, label: str) -> list[str]:
    """What was actually inspected for one input, stated rather than implied."""

    if not inspection.files:
        lines = [f"# {label}: {inspection.path} -- no .csv file found here, so no column"]
        lines.append("#   headers were read from it and nothing below came from it.")
        return lines
    names = ", ".join(f.name for f in inspection.files)
    lines = [f"# {label}: read the header row of {names}"]
    if inspection.skipped_suffixes:
        skipped = ", ".join(inspection.skipped_suffixes)
        lines.append(f"#   Also present and NOT inspected: {skipped} files.")
    return lines


def _render(
    *,
    inspections: Sequence[SourceInspection],
    mapping: dict[str, str],
    stubs: dict[str, str],
    consent_column: str | None,
    consent_candidates: Sequence[str],
    id_column: str | None,
    unmapped: Sequence[str],
    recipe_dir: Path,
) -> str:
    incoming = inspections[-1]
    existing = inspections[0] if len(inspections) > 1 else None

    lines = [
        GENERATED_MARKER,
        "#",
        "# This file does not run yet, on purpose. Every line marked CHOOSE is a",
        "# decision the generator will not make for you. `constituent-reconcile",
        "# validate --config <this file>` names what is still outstanding.",
        "#",
        "# Nothing here was inferred from your data: only the header row of each",
        "# file was read, and a column was mapped only where its header exactly",
        "# matches a documented alias (docs/ADOPTION-KIT.md).",
        "#",
    ]
    if existing is not None:
        lines += _source_comment(existing, "existing")
    lines += _source_comment(incoming, "incoming")
    lines += ["", "[input]"]
    if existing is not None:
        lines.append(f'existing = "{_relative(existing.path, recipe_dir)}"')
    lines.append(f'incoming = "{_relative(incoming.path, recipe_dir)}"')
    if id_column is not None:
        lines.append(f'id_column = "{id_column}"')
    else:
        lines += [
            "# CHOOSE: id_column -- no column header matched a documented alias.",
            "#   Set it to a stable per-row id if your export has one; leave it out if not.",
            '# id_column = "id"',
        ]

    lines += ["", "[mapping]"]
    lines.append("# The value on the right is your column header, copied verbatim.")
    for field in CANONICAL_FIELDS:
        if field in mapping:
            lines.append(f'{field} = "{mapping[field]}"')
        else:
            lines.append(f"# CHOOSE: {field} -- {stubs[field]}.")
            lines.append(f'# {field} = "YOUR COLUMN HEADER"')
    if "first_name" in stubs or "last_name" in stubs:
        lines.append(
            "# first_name and last_name are required; the recipe will not load without them."
        )

    lines += ["", "[consent]"]
    if consent_column is not None:
        lines.append(f'column = "{consent_column}"')
    else:
        reason = (
            "more than one column could be it: " + ", ".join(repr(c) for c in consent_candidates)
            if consent_candidates
            else "no column header matched a documented alias"
        )
        lines += [
            f"# CHOOSE: column -- {reason}.",
            "#   Consent is the gate the write step reads on every field of every record.",
            "#   With no consent column, nothing is exported. Name the column, or decide",
            "#   deliberately that this dataset carries no consent signal.",
            '# column = "Consent"',
        ]
    lines += [
        '# date    = "Consent Date"     # optional: ISO-8601 grant date',
        '# expires = "Consent Expires"  # optional: ISO-8601 expiry; unmapped = no ceiling',
        '# scope   = "Consent Scope"    # optional: comma-separated destinations',
    ]

    lines += [
        "",
        "[thresholds]",
        "# The pre-tuned defaults. Leave them until you have reviewed a real batch.",
        "prior  = 0.01",
        "auto   = 0.97",
        "review = 0.80",
        "",
        "[policy]",
        '# CHOOSE: pack -- choose "default", "dv" or "hipaa"; there is no default here.',
        "#   The pack decides whether personal data may leave this machine.",
        '#     "default" -- general use; the optional cloud extraction seam is permitted.',
        '#     "dv"      -- domestic-violence services: no cloud seam, consent required,',
        "#                  local write targets only, two reviewers, aggregate export.",
        '#     "hipaa"   -- covered-entity posture; see docs/ADOPTION-KIT.md.',
        f'pack = "{UNCHOSEN_POLICY_PACK}"',
    ]

    lines += ["", "# Columns found in your files that this recipe does not use:"]
    if unmapped:
        lines += [f"#   {column}" for column in unmapped]
        lines.append("# They are listed so nothing is dropped without you seeing it. Map any of")
        lines.append("# them above if it belongs to a canonical field.")
    else:
        lines.append("#   (none: every column above is either mapped or a documented stub)")

    return "\n".join(lines) + "\n"


def write(scaffold: Scaffold, out: Path) -> None:
    """Write the recipe, refusing to overwrite anything already at ``out``.

    A recipe is hand-edited configuration. Silently replacing one would destroy an
    operator's mappings, so an existing path is an error whatever it contains.
    """

    if out.exists():
        raise ScaffoldError(
            f"{out} already exists; init will not overwrite a recipe. "
            "Write the scaffold elsewhere with --out and merge it by hand."
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(scaffold.text, encoding="utf-8")


def unfilled_stubs(text: str) -> list[str]:
    """The scaffold CHOOSE lines still outstanding in a recipe's raw text.

    Reads the file as written rather than as loaded, because ``load_recipe``
    raises on the unchosen policy pack before anything could inspect the rest.
    Returns an empty list for a file this module did not generate: the hint is
    about its own output, and guessing at a hand-written recipe would be noise.
    """

    if not text.lstrip().startswith(GENERATED_MARKER):
        return []
    outstanding = [
        line.split("# CHOOSE:", 1)[1].strip()
        for line in text.splitlines()
        if line.lstrip().startswith("# CHOOSE:")
    ]
    # The policy pack's CHOOSE comment survives an operator filling the value in, so
    # it is confirmed against the value rather than the comment.
    if f'pack = "{UNCHOSEN_POLICY_PACK}"' not in text:
        outstanding = [item for item in outstanding if not item.startswith("pack --")]
    return outstanding
